INHERIT: mkdocs-base.yaml

site_name: "Dynatrace Workshop: Scaling Log Analytics"
repo_name: "View Code on GitHub"
repo_url: "https://github.com/dynatrace-wwse/workshop-dynatrace-log-analytics"
nav:
  - "1. About": index.md
  - "2. Getting started": 2-getting-started.md
  - "3. Codespaces": 3-codespaces.md
  - "4. Deploy Dynatrace": 4-deploy-dynatrace.md
  - "5. Scaling Log Analytics": 5-scaling-log-analytics.md
  - "6. Configure Dynatrace": 6-configure-dynatrace.md
  - "7. DQL Exercises": 7-dql-exercises.md
  - "8. Anomaly Detection": 8-anomaly-detection.md
  - "9. Dashboards": 9-dashboards.md
  - "10. Resources": resources.md
  - "11. Cleanup": cleanup.md

extra:
  rum_snippet: "https://js-cdn.dynatrace.com/jstag/1612cf70810/bf81393wlb/d6a688035595a70d_complete.js"
