configs:
- id: "Workshop - Workshop Exercises"
  type:
    document:
      kind: notebook
      private: false
  config:
    name: Workshop - Workshop Exercises
    template: Workshop - Workshop Exercises.json
    parameters:
      dt_platform_url:
        type: environment
        name: DT_PLATFORM_URL
      explore_logs_app_id: ["workshop", "document", "Workshop - Explore Logs App", "id"]
      logs_dql_101_exercises_id: ["workshop", "document", "Workshop - Logs DQL 101 - Exercises", "id"]
      logs_dql_101_answers_id: ["workshop", "document", "Workshop - Logs DQL 101 - Answer Key", "id"]
      logs_dql_102_exercises_id: ["workshop", "document", "Workshop - Logs DQL 102 - Exercises", "id"]
      logs_dql_102_answers_id: ["workshop", "document", "Workshop - Logs DQL 102 - Answer Key", "id"]
      logs_dql_201_exercises_id: ["workshop", "document", "Workshop - Logs DQL 201 - Exercises", "id"]
      logs_dql_201_answers_id: ["workshop", "document", "Workshop - Logs DQL 201 - Answer Key", "id"]
      logs_dql_301_exercises_id: ["workshop", "document", "Workshop - Logs DQL 301 - Exercises with Answer Key", "id"]
      log_metrics_exercises_id: ["workshop", "document", "Workshop - Log Metrics - Exercises", "id"]
      log_metrics_answers_id: ["workshop", "document", "Workshop - Log Metrics - Answer Key", "id"]
      events_exercises_id: ["workshop", "document", "Workshop - Events - Exercises", "id"]
      events_answers_id: ["workshop", "document", "Workshop - Events - Answer Key", "id"]
      copilot_exercises_id: ["workshop", "document", "Workshop - Copilot - Exercises", "id"]
      copilot_answers_id: ["workshop", "document", "Workshop - Copilot - Answer Key", "id"]
- id: "Workshop - Explore Logs App"
  type:
    document:
      kind: notebook
      private: false
  config:
    name: Workshop - Explore Logs App
    template: Workshop - Explore Logs App.json
- id: "Workshop - Logs DQL 101 - Exercises"
  type:
    document:
      kind: notebook
      private: false
  config:
    name: Workshop - Logs DQL 101 - Exercises
    template: Workshop - Logs DQL 101 - Exercises.json
- id: "Workshop - Logs DQL 101 - Answer Key"
  type:
    document:
      kind: notebook
      private: false
  config:
    name: Workshop - Logs DQL 101 - Answer Key
    template: Workshop - Logs DQL 101 - Answer Key.json
- id: "Workshop - Logs DQL 102 - Exercises"
  type:
    document:
      kind: notebook
      private: false
  config:
    name: Workshop - Logs DQL 102 - Exercises
    template: Workshop - Logs DQL 102 - Exercises.json
- id: "Workshop - Logs DQL 102 - Answer Key"
  type:
    document:
      kind: notebook
      private: false
  config:
    name: Workshop - Logs DQL 102 - Answer Key
    template: Workshop - Logs DQL 102 - Answer Key.json
- id: "Workshop - Logs DQL 201 - Exercises"
  type:
    document:
      kind: notebook
      private: false
  config:
    name: Workshop - Logs DQL 201 - Exercises
    template: Workshop - Logs DQL 201 - Exercises.json
- id: "Workshop - Logs DQL 201 - Answer Key"
  type:
    document:
      kind: notebook
      private: false
  config:
    name: Workshop - Logs DQL 201 - Answer Key
    template: Workshop - Logs DQL 201 - Answer Key.json
- id: "Workshop - Logs DQL 301 - Exercises with Answer Key"
  type:
    document:
      kind: notebook
      private: false
  config:
    name: Workshop - Logs DQL 301 - Exercises with Answer Key
    template: Workshop - Logs DQL 301 - Exercises with Answer Key.json
- id: "Workshop - Log Metrics - Exercises"
  type:
    document:
      kind: notebook
      private: false
  config:
    name: Workshop - Log Metrics - Exercises
    template: Workshop - Log Metrics - Exercises.json
- id: "Workshop - Log Metrics - Answer Key"
  type:
    document:
      kind: notebook
      private: false
  config:
    name: Workshop - Log Metrics - Answer Key
    template: Workshop - Log Metrics - Answer Key.json
- id: "Workshop - Events - Exercises"
  type:
    document:
      kind: notebook
      private: false
  config:
    name: Workshop - Events - Exercises
    template: Workshop - Events - Exercises.json
- id: "Workshop - Events - Answer Key"
  type:
    document:
      kind: notebook
      private: false
  config:
    name: Workshop - Events - Answer Key
    template: Workshop - Events - Answer Key.json
- id: "Workshop - Copilot - Exercises"
  type:
    document:
      kind: notebook
      private: false
  config:
    name: Workshop - Copilot - Exercises
    template: Workshop - Copilot - Exercises.json
- id: "Workshop - Copilot - Answer Key"
  type:
    document:
      kind: notebook
      private: false
  config:
    name: Workshop - Copilot - Answer Key
    template: Workshop - Copilot - Answer Key.json