apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-envs
data:
  MSSQL_CONNECTIONSTRING: "Data Source=db;Initial Catalog=TradeManagement;Persist Security Info=True;User ID=sa;Password=yourStrong(!)Password;TrustServerCertificate=true"
  PROXY_PREFIX: "manager"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
spec:
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
        - name: manager
          image: gcr.io/dynatrace-demoability/easytrade/manager:f505fb9
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: manager-envs
          - configMapRef:
              name: flagsmith-setup
          resources:
            requests:
              cpu: 150m
              memory: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  name: manager
spec:
  type: ClusterIP
  selector:
    app: manager
  ports:
    - name: http
      port: 80
      targetPort: 80