apiVersion: apps/v1
kind: Deployment
metadata:
  name: newfrontend
spec:
  selector:
    matchLabels:
      app: newfrontend
  template:
    metadata:
      labels:
        app: newfrontend
    spec:
      containers:
        - name: newfrontend
          image: gcr.io/dynatrace-demoability/easytrade/newfrontend:f505fb9
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 300m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: newfrontend
spec:
  type: ClusterIP
  selector:
    app: newfrontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000