apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: gcr.io/dynatrace-demoability/easytrade/postgres:f505fb9
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: flagsmith
        - name: POSTGRES_PASSWORD
          value: password
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
