x-logging: &default-logging
  driver: json-file
  options:
    max-file: "5"
    max-size: "10m"

x-service: &default-service
  restart: always
  logging: *default-logging

x-aggregator-service: &default-aggregator-service
  <<: *default-service
  image: ${REGISTRY}/aggregatorservice:${TAG}
  depends_on:
    - offerservice

x-aggregator-service-env: &default-aggregator-service-env
  NODE_ENV: production
  OFFER_SERVICE: offerservice:8080

x-flagsmith: &flagsmith-env
  FLAGSMITH_PROJECT: easytrade
  FLAGSMITH_PROTOCOL: http
  FLAGSMITH_BASE_URL: flagsmith
  FLAGSMITH_PORT: 8000
  FLAGSMITH_PASS: adminpass123
  FLAGSMITH_EMAIL: admin@mail.com
  FLAGSMITH_ENV_KEY: ${FLAGSMITH_ENV_KEY}

services:
  db:
    <<: *default-service
    image: ${REGISTRY}/db:${TAG}
    environment:
      SA_PASSWORD: yourStrong(!)Password
  postgres:
    hostname: postgres
    container_name: postgres
    image: ${REGISTRY}/postgres:${TAG}
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flagsmith  
  contentcreator:
    <<: *default-service
    image: ${REGISTRY}/contentcreator:${TAG}
    depends_on:
      - db
    environment:
      MSSQL_CONNECTIONSTRING: jdbc:sqlserver://db:1433;database=TradeManagement;user=sa;password=yourStrong(!)Password;encrypt=false;trustServerCertificate=false;loginTimeout=30;

  manager:
    <<: *default-service
    image: ${REGISTRY}/manager:${TAG}
    depends_on:
      - db
    environment:
      <<: *flagsmith-env
      MSSQL_CONNECTIONSTRING: Data Source=db;Initial Catalog=TradeManagement;Persist Security Info=True;User ID=sa;Password=yourStrong(!)Password;TrustServerCertificate=true
      PROXY_PREFIX: manager

  pricing-service:
    <<: *default-service
    image: ${REGISTRY}/pricing-service:${TAG}
    depends_on:
      - db
      - rabbitmq
    environment:
      MSSQL_CONNECTIONSTRING: sqlserver://sa:yourStrong(!)Password@db:1433?database=TradeManagement&connection+encrypt=false&connection+TrustServerCertificate=false&connection+loginTimeout=30
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: userxxx
      RABBITMQ_PASSWORD: passxxx
      RABBITMQ_QUEUE: Trade_Data_Raw
      PROXY_PREFIX: pricing-service

  brokerservice:
    <<: *default-service
    image: ${REGISTRY}/brokerservice:${TAG}
    depends_on:
      - manager
      - accountservice
      - pricing-service
    environment:
      MANAGER_HOSTANDPORT: manager:80
      ACCOUNTSERVICE_HOSTANDPORT: accountservice:8080
      PRICINGSERVICE_HOSTANDPORT: pricing-service:80
      PROXY_PREFIX: broker

  rabbitmq:
    <<: *default-service
    image: ${REGISTRY}/rabbitmq:${TAG}

  calculationservice:
    <<: *default-service
    image: ${REGISTRY}/calculationservice:${TAG}
    depends_on:
      - rabbitmq

  frontend:
    <<: *default-service
    image: ${REGISTRY}/frontend:${TAG}
    depends_on:
      - brokerservice
      - loginservice
      - pricing-service
      - accountservice

  newfrontend:
    <<: *default-service
    image: ${REGISTRY}/newfrontend:${TAG}

  loginservice:
    <<: *default-service
    image: ${REGISTRY}/loginservice:${TAG}
    depends_on:
      - db
    environment:
      MSSQL_CONNECTIONSTRING: Data Source=db;Initial Catalog=TradeManagement;Persist Security Info=True;User ID=sa;Password=yourStrong(!)Password;TrustServerCertificate=true
      PROXY_PREFIX: login

  frontendreverseproxy:
    <<: *default-service
    image: ${REGISTRY}/frontendreverseproxy:${TAG}
    depends_on:
      - brokerservice
      - frontend
      - newfrontend
      - loginservice
      - pricing-service
      - flagsmith
      - offerservice
      - accountservice
      - engine
    ports:
      - 80:80
      - 8000:8000

  headlessloadgen:
    <<: *default-service
    image: gcr.io/dynatrace-demoability/headlessloadgen:${LOADGEN_TAG}
    depends_on:
      - frontendreverseproxy
    environment:
      EASY_TRADE_DOMAIN: frontendreverseproxy
      EASY_TRADE_PORT: 80

  offerservice:
    <<: *default-service
    image: ${REGISTRY}/offerservice:${TAG}
    depends_on:
      - loginservice
      - manager
    environment:
      <<: *flagsmith-env
      LOGIN_SERVICE_PORT: 80
      LOGIN_SERVICE_BASE_URL: loginservice
      MANAGER_BASE_URL: manager
      MANAGER_PORT: 80

  flagsmith:
    hostname: flagsmith
    container_name: flagsmith
    image: ${REGISTRY}/flagsmith:${TAG}
    depends_on:
      - postgres
    environment:
      <<: *flagsmith-env
      DJANGO_ALLOWED_HOSTS: "*"
      DATABASE_URL: postgresql://postgres:password@postgres:5432/flagsmith
      DISABLE_INFLUXDB_FEATURES: "true" # set to 'false' to enable InfluxDB
      ENV: prod
    restart: always

  accountservice:
    <<: *default-service
    image: ${REGISTRY}/accountservice:${TAG}
    depends_on:
      - manager
    environment:
      MANAGER_HOSTANDPORT: manager:80
      PROXY_PREFIX: accountservice

  engine:
    <<: *default-service
    image: ${REGISTRY}/engine:${TAG}
    depends_on:
      - brokerservice
    environment:
      BROKER_HOSTANDPORT: brokerservice:80
      PROXY_PREFIX: engine

  aggregatorservice_1:
    <<: *default-aggregator-service
    environment:
      <<: *default-aggregator-service-env
      PLATFORM: dynatestsieger.at
      STARTER_PACKAGE_PROBABILITY: 0.6
      LIGHT_PACKAGE_PROBABILITY: 0.3
      PRO_PACKAGE_PROBABILITY: 0.1

  aggregatorservice_2:
    <<: *default-aggregator-service
    environment:
      <<: *default-aggregator-service-env
      PLATFORM: tradeCom.co.uk
      STARTER_PACKAGE_PROBABILITY: 0.8
      LIGHT_PACKAGE_PROBABILITY: 0.2
      PRO_PACKAGE_PROBABILITY: 0

  aggregatorservice_3:
    <<: *default-aggregator-service
    environment:
      <<: *default-aggregator-service-env
      PLATFORM: CryptoTrading.com
      FILTER: '["Crypto"]'
      MAXFEE: 0
      STARTER_PACKAGE_PROBABILITY: 0.5
      LIGHT_PACKAGE_PROBABILITY: 0.4
      PRO_PACKAGE_PROBABILITY: 0.1

  aggregatorservice_4:
    <<: *default-aggregator-service
    environment:
      <<: *default-aggregator-service-env
      PLATFORM: CheapTrading.mi
      MAXFEE: 0
      STARTER_PACKAGE_PROBABILITY: 1
      LIGHT_PACKAGE_PROBABILITY: 0
      PRO_PACKAGE_PROBABILITY: 0

  aggregatorservice_5:
    <<: *default-aggregator-service
    environment:
      <<: *default-aggregator-service-env
      PLATFORM: Stratton-oakmount.com
      FILTER: '["Shares"]'
      STARTER_PACKAGE_PROBABILITY: 0
      LIGHT_PACKAGE_PROBABILITY: 0.1
      PRO_PACKAGE_PROBABILITY: 0.9